### ISSUE TITLE
Create a `CONTINUE` verdict

### ISSUE THREAD

**Issue by qdeslandes** [facebook/bpfilter#103]
With the existing verdicts, it's not possible to forward a packet to the next rule: it is either accepted or dropped. In both cases, the chain won't process the remaining rules.

A `CONTINUE` verdict would allow packets to continue going through the filtering rules. Currently, the main interest of such a target would be to count the packets matching specific criteria. For example, this is not currently possible

```shell
# Counter the number of IPv6 packets and TCP packets going through the hook
rule
    meta.l3_proto ip6
    counter
    ACCEPT
rule
    meta.l4_proto tcp
    counter
    ACCEPT
```

IPv6 TCP packets would be counted towards rule #1 counter, as every IPv6 packet would be matched by rule #1 and accepted, stopping the processing. However, with a `CONTINUE` verdict:

```shell
# Counter the number of IPv6 packets and TCP packets going through the hook
rule
    meta.l3_proto ip6
    counter
    CONTINUE
rule
    meta.l4_proto tcp
    counter
    CONTINUE
```

IPv6 TCP packet would be processed by rule #1 and counted, then processing would continue with rule #2 and they would be counted again.

**Comment by ryantimwilson** [comment]
Hey @qdeslandes I'll take this if you don't mind.

For consistency with nftables, seems:
1. We shouldn't allow CONTINUE for chains, only ACCEPT and DROP: https://wiki.nftables.org/wiki-nftables/index.php/Quick_reference-nftables_in_10_minutes. I can add validation for this in bf_chain_new()
2. CONTINUE is allowed for matchers, but I wonder if we should allow it for matchers without `counter` as it doesn't seem fruitful. But there seems no harm done in allowing it other than wasted CPU cycles.

Seems straightforward to implement by just not returning the verdict in _bf_program_generate_rule in program.c and letting us fall through to the next rule:
```
if (rule->verdict != CONTINUE) {
    EMIT(program, BPF_MOV64_IMM(BF_REG_RET, program->runtime.ops->get_verdict(
                                                rule->verdict)));
    EMIT(program, BPF_EXIT_INSN());
}
```

I don't *think* a jump to the next rule is needed for CONTINUE as we'll just fall through...but I will confirm that in testing :)

**Comment by qdeslandes** [comment]
> Hey @qdeslandes I'll take this if you don't mind.
> 
> Some notes:
> 
> 1. For consistency with nftables, seems we shouldn't allow CONTINUE for chains, only ACCEPT and DROP: https://wiki.nftables.org/wiki-nftables/index.php/Quick_reference-nftables_in_10_minutes. I can add validation for this in bf_chain_new()

Agreed, `CONTINUE` should be limited to rules verdict. For reference: chains can't (at least for now) be chained one after the other, and `CONTINUE` is about deferring the verdict to the next entity. So had we decided to support `CONTINUE` for chains, there would be no entity afterward to apply a verdict.

> 2. CONTINUE is allowed for matchers, but I wonder if we should allow it for matchers without `counter` as it doesn't seem fruitful. But there seems no harm done in allowing it other than wasted CPU cycles.

I think you mean "rules" here, and I agree with your point. I would lean on the side of doing the simplest, most predictable implementation from the user's point-of-view. IMO that would be to allow a rule to `CONTINUE` even if no `counter` is defined. It's a malformed, useless rule, but valid from `bpfilter`'s perspective.

> Seems straightforward to implement by just not returning the verdict in _bf_program_generate_rule in program.c and letting us fall through to the next rule:
> 
> ```
> if (rule->verdict != CONTINUE) {
>     EMIT(program, BPF_MOV64_IMM(BF_REG_RET, program->runtime.ops->get_verdict(
>                                                 rule->verdict)));
>     EMIT(program, BPF_EXIT_INSN());
> }
> ```
> 
> I don't _think_ a jump to the next rule is needed for CONTINUE as we'll just fall through...but I will confirm that in testing :)

Your understanding is correct! Also, this behaviour should be documented in `bfcli.rst`, the user should be aware that if a rule uses `CONTINUE`, a given packet could be counted more than once!
