### ISSUE TITLE
Collect error metrics

### ISSUE THREAD

**Issue by qdeslandes** [facebook/bpfilter#105]
Generated BPF programs call `kfunc`s and BPF helpers for various purposes, and those call might fail. In this situation, the program will return with a default verdict. There is currently no way to know if such an error occurred during the program's lifetime, except for reading `/sys/kernel/debug/tracing/trace_pipe` if `bpfilter` is running in debug mode (`--debug`).

An error/failure counter would bring more visibility to this situation and help to understand the program's behavior.

**Comment by amscanne** [comment]
I started looking at this as a learning exercise, and have posted a draft in #154. I'd love feedback/direction on this (i.e. if the approach makes sense, what the best way to best an integration test for the `nft` communication bits, etc.) if such a contribution is friendly!
