### ISSUE TITLE
LAB testing

### ISSUE THREAD

**Issue by danielkornuta** [facebook/bpfilter#31]
Hi , I install it but when i use iptables with option i have error iptables v1.8.9 (nf_tables): unknown option "--bpf".
How to install it correctly and using it?
i already start it @bpfilter/build/src# ./bpfilter
info   : restored new codegen at 0x8006f0
info   : restored new codegen at 0x800bb0
info   : restored new codegen at 0x801070
info   : cache already initialised, skipping initialisation
info   : waiting for requests...

**Comment by qdeslandes** [comment]
Hi @danielkornuta 

It seems like you're using the `iptables` binary provided with your distribution, which doesn't support the `--bpf` option. I've opened PR #32 to fix this by adding some documentation for this process. Can you follow its [instructions here](https://github.com/qdeslandes/bpfilter/blob/document_iptables_build/doc/iptables.md) and see how it works for you? 

Do not hesitate to answer to this comment if something doesn't work on your end, I'll update the documentation!

Thanks,
Quentin

**Comment by danielkornuta** [comment]
Thanks for your time! I'm currently stuck in this step: "./autogen.sh"

Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 274.
autoreconf: error: aclocal failed with exit status: 2

Looking forward to use it, i see your presentations and looks promising ;)

**Comment by dominix** [comment]
aclocal seem to be part of automake. you may need to install automake ...

**Comment by qdeslandes** [comment]
Dominix is right, you're missing the `automake` package (Fedora/Ubuntu), for other distros it might have a different name.

**Comment by danielkornuta** [comment]
Hi :) i'm going forward with this, but stuck at different point. I hope I make it properly.

# ./autogen.sh
PKG_CONFIG_PATH=$INSTALL_DIRECTORY/share/pkgconfig ./configure \
    --prefix=$INSTALL_DIRECTORY \
    --disable-nftables \
    --enable-libipq \
    --enable-bpfilter
libipq/Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
libipq/Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libipq/Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libipq/Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
libipq/Makefile.am:8:   its definition is in aclocal's search path.
libiptc/Makefile.am:9: error: Libtool library used but 'LIBTOOL' is undefined
libiptc/Makefile.am:9:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libiptc/Makefile.am:9:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libiptc/Makefile.am:9:   If 'LT_INIT' is in 'configure.ac', make sure
libiptc/Makefile.am:9:   its definition is in aclocal's search path.
libxtables/Makefile.am:7: error: Libtool library used but 'LIBTOOL' is undefined
libxtables/Makefile.am:7:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libxtables/Makefile.am:7:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libxtables/Makefile.am:7:   If 'LT_INIT' is in 'configure.ac', make sure
libxtables/Makefile.am:7:   its definition is in aclocal's search path.
autoreconf: error: automake failed with exit status: 1
configure: WARNING: unrecognized options: --enable-bpfilter
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
./configure: line 4806: syntax error near unexpected token `disable-static'
./configure: line 4806: `LT_INIT(disable-static)'

**Comment by danielkornuta** [comment]
Hi, for now I'm here:
configure: error: missing bpfilter library required for bpfilter support

Everything made correctly at this moment. What to do now Quentin?:)
Trying a lot of times, without success:/

**Comment by danielkornuta** [comment]
Another error occurs, few steps ahead:

configure: error: missing bpfilter library required for bpfilter support

**Comment by danielkornuta** [comment]
You can close. Working properly ;) looking forward to tutorial using nftables.

**Comment by qdeslandes** [comment]
Great! The `nftables` guide is in progress ;)
